### ISSUE TITLE
stale viewers

### ISSUE THREAD

**Issue by gtimoth** [bacwyls/radio#1]

**Comment by gtimoth** [comment]
alert on window close to buy time for the tuneout poke

**Comment by tomholford** [comment]
> alert on window close to buy time for the tuneout poke

Maybe an unload event listener?

https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

**Comment by gtimoth** [comment]
im sending a poke to exit the radio station on beforeunload, it just doesnt always get there

**Comment by gtimoth** [comment]
solved with 3minute heartbeat and 6minute timeout
